### ISSUE TITLE
Implement 12-key flick keyboard for Japanese input

### ISSUE THREAD

**Issue by ynakao** [fcitx5-android/fcitx5-android#375]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**

Most Japanese speakers use [12-key flick keyboard](https://en.wikipedia.org/wiki/Japanese_input_method#Flick_input) on mobile devices, which is [widely used](https://ja.wikipedia.org/wiki/%E3%83%95%E3%83%AA%E3%83%83%E3%82%AF%E5%85%A5%E5%8A%9B#%E3%83%95%E3%83%AA%E3%83%83%E3%82%AF%E5%85%A5%E5%8A%9B%E3%81%8C%E5%8F%AF%E8%83%BD%E3%81%AA%E4%B8%BB%E3%81%AA%E6%A9%9F%E5%99%A8%E3%83%BB%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%85%A5%E5%8A%9B%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0) in like iOS and Google Japanese Input(Mozc) on Android and so on. It would be great to implement the flick keyboard for Japanese input on fcitx5-android in the same way.

![12key-Japanese-input-mozc](https://github.com/fcitx5-android/fcitx5-android/assets/6405335/3248af26-0766-44b4-9eb6-bec3ac00cfbe)

**描述解决方案 / Describe the solution you'd like**

Implement 12-key flick keyboard for Japanese input.

**描述替代方案 / Describe alternatives you've considered**

None.

**附加信息 / Additional context**

None.

**Comment by oldherl** [comment]
Currently the layout is fixed to QWERTY. Would need #109 to be implemented before any other layouts are added.

**Comment by rocka** [comment]
This should be separated into 2 parts:

1. port some engine that actually has support for 12-key flick input mode
2. implement keyboard layout for that engine #377

I'm aware that Mozc for Android has 12-key support, but

1. Mozc's Android InputMethodService implementation has been deleted and unsupported since https://github.com/google/mozc/commit/a1dcadabd3a1c604e8beff1e45830c1d9adfce84 , nobody (i.e. our developers) is familiar with that code base.
2. [fcitx5-mozc](https://github.com/fcitx/mozc/tree/fcitx/src/unix/fcitx5)'s usage of mozc turns to be very diffenret from mozc's own Android implementation, until now nobody has ever tried to build it for Android, I wonder whether it would run (even build) at all.
3. If I've understood it correctly, 12-key flick keyboard requires the user swipe on the keyboard to trigger input, every key can either be pressed or swipe in 4 directions, which current keypress detection logic does not support. And I'm not sure how to pass "swipe gesture" from Android keyboard frontend to input method engine.

Until all those problems are solved, I'm afraid this feature won't be implemented any time soon.

**Comment by ynakao** [comment]
Just for reference, there is [SKK for Android (Japanese website)](http://ray-mizuki.la.coocan.jp/software/skk_jp.html) which implements a flick keyboard and [SKK](http://openlab.jp/skk/index.html) as a backend engine.

You can get [the source code](http://ray-mizuki.la.coocan.jp/software/files/AndroidSKK-source.zip) from the site and check the implementation.

**Comment by rocka** [comment]
I tried AndroidSKK 3.5.1 on my phone, it does support flick input and is able to input kana and kanji (just need to press <kbd>↑</kbd> on top left corner before typing kanji).

I wonder does it host source code on git repository somewhere else? I found https://github.com/xiupos/android-skk from googling but it seems different from this one.

**Comment by ynakao** [comment]
It seems there's no public git repository, but only the source code zip he provided unfortunately. And the one you mentioned is a forked version. I'm also concerned there's no LICENSE file in the source code.

He writes [blog posts (also in Japanese)](https://www.di-do.net/ray_m/?category=101r&option=all&page=1) about AndroidSKK, so it is possible to contact him to ask them. In [one post](https://www.di-do.net/ray_m/?201703-1490319962000#1490319962000), he said "I could send a git bundle file if you contacted me".

**Comment by rocka** [comment]
this should be merged into #377
