### ISSUE TITLE
Consider expose internal input method to system on Android 14

### ISSUE THREAD

**Issue by scrpr** [fcitx5-android/fcitx5-android#386]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**
Before Android 14 (API 34), it is advised to expose only one unified [InputMethodSubtype](https://developer.android.com/reference/android/view/inputmethod/InputMethodSubtype) to system as there is no convenient API which allows the IME dynamically changes supported subtypes.
在 Android 14 (API 34)之前，支持多语言的输入法都只暴露一个统一的subtype给系统，因为当时并没有动态修改subtype的API。

**描述解决方案 / Describe the solution you'd like**
However, a new method introduced in API 34, namely [setExplicitlyEnabledInputMethodSubtypes](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#setExplicitlyEnabledInputMethodSubtypes(java.lang.String,%20int[])), does allow IMEs change their subtypes in runtime using [InputMethodSubtypeBuilder](https://developer.android.com/reference/android/view/inputmethod/InputMethodSubtype.InputMethodSubtypeBuilder), and Gboard has already implemented this. It would be nice if fcitx5-android support this new feature.
但是Android 14引入了一项新[API]((https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#setExplicitlyEnabledInputMethodSubtypes(java.lang.String,%20int[])))，可以让输入法在运行时更改显式启用的subtype，这样一来动态指定subtype就成为了可能。观察到Gboard已经实现了这项特性，在系统输入法选择菜单中会分别显示所有已启用的语言和键盘，如果fcitx5-android也能支持这一特性就好了。

**Comment by rocka** [comment]
This API can only "Enable" some already existing subMode, but not creating new subModes on runtime, because

> (InputMethodSubtype) should be defined in an XML resource file

https://developer.android.com/reference/android/view/inputmethod/InputMethodSubtype

For gboard it's fine, since they only support a fixed number of languages which won't be changed after the App has been compiled. But we do support a variable amount of plugins, also user can import their own table-based input methods, resulting new "Subtype"s. I wonder whether it can be implemented using those new APIs.

**Comment by scrpr** [comment]
> This API can only "Enable" some already existing Subtype, but not creating new Subtype on runtime, because
> 
> > (InputMethodSubtype) should be defined in an XML resource file
> 

@rocka Well, it is not true in API 34. By using [InputMethodSubtypeBuilder](https://developer.android.com/reference/android/view/inputmethod/InputMethodSubtype.InputMethodSubtypeBuilder) you can actually create a new subtype without having to predefine in the XML. This builder was initially used to coorporate with [setAdditionalInputMethodSubtypes](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#setAdditionalInputMethodSubtypes(java.lang.String,%20android.view.inputmethod.InputMethodSubtype[])), but since it has been deprecated, [setExplicitlyEnabledInputMethodSubtypes](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#setExplicitlyEnabledInputMethodSubtypes(java.lang.String,%20int%5B%5D)) seems to be a better alternative.
![dynamic subtype](https://github.com/fcitx5-android/fcitx5-android/assets/46473171/4087b53b-8aa2-40fe-a786-3bacf46d0a6b)

**Comment by rocka** [comment]
It turns out you have to use the deprecated [InputMethodManager#setAdditionalInputMethodSubtypes](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#setAdditionalInputMethodSubtypes(java.lang.String,%20android.view.inputmethod.InputMethodSubtype%5B%5D)) to "register" those dynamic subtypes before they can be enabled by [setExplicitlyEnabledInputMethodSubtypes](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#setExplicitlyEnabledInputMethodSubtypes(java.lang.String,%20int%5B%5D))

Should be fixed by a2a67fc
